[package]
name = "asteroids-core"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = []

[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }

[dev-dependencies]
serde_json = "1.0"
