[package]
name = "asteroids_verify"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "^3.0.5", default-features = false, features = ['std'] }
asteroids-core = { path = "../../core", default-features = false }
serde = { version = "1.0", default-features = false }
