[package]
name = "asteroids-verify"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
asteroids-core = { path = "../../core", default-features = false }
risc0-zkvm = { version = "^3.0.3", default-features = false, features = ["std"] }

[features]
cycle-prof = []
