[package]
name = "asteroids-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive"] }

[features]
default = ["std"]
std = ["serde/std"]
guest = ["serde/alloc"]
