[package]
name = "verify_tape"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
asteroids-verifier-core = { path = "../../asteroids-core", default-features = false }
risc0-zkvm = { version = "^3.0.5", default-features = false }
